name: Compile LaTeX (Master)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Compiling LaTeX documents
      - name: Compiling LaTeX documents
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          working_directory: src
          args: -pdf -halt-on-error -synctex=1 -interaction=nonstopmode --shell-escape --enable-write18
          extra_system_packages: 'inkscape openjdk17'
          docker_image: ghcr.io/xu-cheng/texlive-full:20240315

      - name: Prepare GitHub Pages publish dir
        run: |
          mkdir -p public
          cp src/main.pdf public/

      - name: Upload artifact (PDF)
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: src/main.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
